"""empty message

Revision ID: 7c48221537b4
Revises: 766dfc82cfb4
Create Date: 2020-04-19 13:58:21.796880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c48221537b4'
down_revision = '766dfc82cfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_column('rating', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('rating', 'user_id')
    # ### end Alembic commands ###
